SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    SUB.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA AS E
    JOIN (SELECT 
          YEAR(DIFFERENTIATION_DATE) AS YEAR,
          MAX(SIZE_OF_COLONY) AS MAX_SIZE
         FROM ECOLI_DATA
         GROUP BY YEAR(DIFFERENTIATION_DATE)) AS SUB
    ON YEAR(E.DIFFERENTIATION_DATE) = SUB.YEAR
ORDER BY YEAR, YEAR_DEV